export const authorIdToName: Record<string, string> = {
  ammianus: 'ammianus marcellinus',
  apuleius: 'lucius apuleius madaurensis',
  augustus: 'caesar divi filius augustus',
  'aurelius victor': 'sextus aurelius victor',
  caesar: 'gaius iulius caesar',
  cato: 'marcus porcius cato censor',
  catullus: 'gaius valerius catullus',
  cicero: 'marcus tullius cicero',
  claudian: 'claudius claudianus',
  'curtius rufus': 'quintus curtius rufus',
  ennius: 'quintus ennius',
  eutropius: 'eutropius',
  florus: 'florus',
  frontinus: 'sextus iulius frontinus',
  gellius: 'aulus gellius',
  'historia augusta': 'scriptores historiae augustae',
  horace: 'quintus horacius flaccus',
  'roman law': 'ius romanum',
  justin: 'marcus iunianus iustinus',
  juvenal: 'decimus iunius iuvenalis',
  livy: 'titus livius',
  lucan: 'marcus annaeus lucanus',
  lucretius: 'titus lucretius carus',
  martial: 'marcus valerius martialis',
  nepos: 'cornelius nepos',
  ovid: 'publius ovidius naso',
  persius: 'aulus persius flaccus',
  petronius: 'gaius petronius',
  phaedrus: 'phaedrus',
  plautus: 'titus maccius plautus',
  'pliny maior': 'gaius plinius secundus',
  'pliny minor': 'gaius plinius caecilius secundus',
  propertius: 'sextus propertius',
  quintilian: 'marcus fabius quiintilianus',
  sallust: 'gaius sallustius crispus',
  'seneca maior': 'lucius annaeus seneca maior',
  'seneca minor': 'lucius annaeus seneca',
  'silius italicus': 'silius italicus',
  statius: 'publius papinius statius',
  suetonius: 'gaius suetonius tranquillus',
  sulpicia: 'sulpicia',
  tacitus: 'publius cornelius tacitus',
  terence: 'publius terentius afer',
  tibullus: 'albius tibullus',
  'valerius flaccus': 'gaius valereius flaccus',
  'valerius maximus': 'valerius maximus',
  varro: 'marcus terentius varro',
  vellius: 'gaius velleius patereculus',
  virgil: 'publius vergilius maro',
  vitruvius: 'marcus vitruvius pollio',
  'vulgate bible old testament': 'biblia sacra vulgata testamentum vetum',
  'vulgate bible new testament': 'biblia sacra vulgata testamentum novum',
}

export const bookNameMap: Record<string, string> = {
  'commentariorum libri vii de bello gallicocum a. hirti supplemento':
    'de bello gallico',
  'commentariorum libri iii de bello civili': 'de bello civili',
  'libri incertorum auctorum': '',
}

export const worksMap: Record<string, string> = {
  aen: 'aeneid',
  ec: 'eclogues',
  geo: 'georgicon',
  gall: 'de bello gallico',
  bc: 'de bello civili',
  alex: 'de bello alexandrino',
  bellafr: 'de bello africo',
  hisp: 'de bello hispaniensi',
  met: 'metamorphoses',
  amor: 'amores',
  her: 'heroides',
  artis: 'ars amatoria',
  tristia: 'tristia',
  ponto: 'ex ponto',
  fasti: 'fasti',
  rem: 'remedia amoris',
  ibis: 'ibis',
  pontoalone: 'ponto',
  resgestae: 'res gestae divi augusti',
}
