version: "3"
services:
  database:
    image: postgres:13
    container_name: database
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ./data/database_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.11.1
  #   container_name: kibana
  #   ports:
  #     - 5601:5601
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #     ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
  #   depends_on:
  #     - elasticsearch

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
  #   container_name: elasticsearch
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - ./data/elasticsearch_volume:/usr/share/elasticsearch/data
  #   environment:
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "curl --fail http://elasticsearch:9200/_cluster/health || exit 1",
  #       ]
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1

volumes:
  database_volume:
    driver: local
  # elasticsearch_volume:
  #   driver: local
