apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
spec:
  tls:
    - secretName: tls-dev
      hosts:
        - dev.lexicolatin.com
  rules:
    - host: dev.lexicolatin.com
      http:
        paths:
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
