version: "3"
services:
  web:
    image: jimmypaolini/lexico-web
    build:
      context: .
      dockerfile: ./web.Dockerfile
    container_name: web
    env_file: ../../.env
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    image: jimmypaolini/lexico-server
    build:
      context: .
      dockerfile: ./server.Dockerfile
    container_name: server
    ports:
      - 3001:3001
    env_file: ../../.env
    depends_on:
      - database
      - elasticsearch
