version: "3"
services:
  server:
    image: jimmypaolini/lexico-server
    build:
      context: .
      dockerfile: ./server.Dockerfile
    container_name: server
    ports:
      - 3001:3001
    env_file: ../../.env
    depends_on:
      - database

  database:
    image: postgres:13
    container_name: database
    ports:
      - 5432:5432
    env_file: ../../.env
    volumes:
      - ../../data/database_volume:/var/lib/postgresql/data

volumes:
  database_volume:
    driver: local
