version: '3'
services:
  database:
    image: postgres:13
    container_name: database
    ports:
      - 5432:5432
    env_file: ../../.env
    volumes:
      - ../../data/database_volume:/var/lib/postgresql/data

volumes:
  database_volume:
    driver: local
