apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  labels:
    app: database
spec:
  serviceName: database
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: env
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-pvc
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #             - key: app
      #               operator: In
      #               values:
      #                 - database
      #         topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
    - metadata:
        name: database-pvc
        labels:
          app: database
      spec:
        storageClassName: linode-block-storage-retain
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
kind: Service
apiVersion: v1
metadata:
  name: database
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: database
