# https://github.com/bitnami/charts/tree/master/bitnami/postgresql/values.yaml

fullnameOverride: database

resources:
  requests:
    cpu: 250m
    memory: 256Mi

primary:
  podAntiAffinityPreset: hard
readReplicas:
  podAntiAffinityPreset: hard
