# https://github.com/bitnami/charts/tree/master/bitnami/postgresql/values.yaml

fullnameOverride: database

resources:
  requests:
    cpu: 250m
    memory: 256Mi

# extraEnvVarsCM: env

postgresqlUsername: postgres
postgresqlDatabase: lexico
postgresqlPassword: xxx

replication:
  enabled: true
  readReplicas: 3
  applicationName: database
  user: postgres
  password: xxx
readReplicas:
  podAntiAffinityPreset: hard
primary:
  podAntiAffinityPreset: hard

extraEnv:
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: env
        key: POSTGRES_USER
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: env
        key: POSTGRES_PASSWORD
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: env
        key: POSTGRES_DB
  - name: POSTGRESQL_USERNAME
    valueFrom:
      secretKeyRef:
        name: env
        key: POSTGRES_USER
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: env
        key: POSTGRES_PASSWORD
  - name: POSTGRESQL_DATABASE
    valueFrom:
      secretKeyRef:
        name: env
        key: POSTGRES_DB
  - name: PGDATA
    valueFrom:
      secretKeyRef:
        name: env
        key: PGDATA
  - name: POSTGRES_HOST_AUTH_METHOD
    valueFrom:
      secretKeyRef:
        name: env
        key: POSTGRES_HOST_AUTH_METHOD
