# https://github.com/bitnami/charts/tree/master/bitnami/postgresql/values.yaml

fullnameOverride: database

extraEnvVarsCM: env

postgresqlUsername: postgres
postgresqlDatabase: lexico
postgresqlPassword: xxx

replication:
  enabled: true
  readReplicas: 3
  applicationName: database
  user: postgres
  password: xxx
readReplicas:
  podAntiAffinityPreset: hard
primary:
  podAntiAffinityPreset: hard

resources:
  requests:
    cpu: 250m
    memory: 256Mi
