# https://github.com/elastic/helm-charts/blob/master/kibana/values.yaml

fullnameOverride: kibana
imageTag: "7.12.0"

elasticsearchHosts: http://elasticsearch:9200

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 100m
    memory: 256Mi

extraEnvs:
  - name: SERVER_PORT # This env variable must have its default overridden
    value: "5601"
