# https://github.com/elastic/helm-charts/blob/master/kibana/values.yaml

fullnameOverride: kibana
elasticsearchHosts: http://elasticsearch:9200

resources:
  requests:
    cpu: 250m
    memory: 512Mi

readinessProbe:
  failureThreshold: 10
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

extraEnvs:
  - name: SERVER_PORT # This env variable must have its default overridden
    value: "5601"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - elasticsearch
            - key: statefulset.kubernetes.io/pod-name
              operator: In
              values:
                - database-primary-0
        topologyKey: kubernetes.io/hostname
