# https://github.com/elastic/helm-charts/blob/master/kibana/values.yaml

fullnameOverride: kibana
elasticsearchHosts: http://elasticsearch:9200

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1024Mi

extraEnvs:
  - name: SERVER_PORT # This env variable must have its default overridden
    value: "5601"

readinessProbe:
  failureThreshold: 10
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10
