export default [
  { name: "typescript", url: "https://www.typescriptlang.org" },
  { name: "nodejs", url: "https://nodejs.org" },
  { name: "postgres", url: "https://www.postgresql.org" },
  { name: "expressjs", url: "https://expressjs.com" },
  { name: "typeorm", url: "https://typeorm.io" },
  { name: "graphql", url: "https://graphql.org" },
  { name: "apollo", url: "https://www.apollographql.com" },
  { name: "type-graphql", url: "https://typegraphql.com" },
  { name: "elk", url: "https://www.elastic.co" },
  { name: "fluentbit", url: "https://fluentbit.io" },
  { name: "sendgrid", url: "https://sendgrid.com" },
  { name: "jwt", url: "https://jwt.io" },
  { name: "nextjs", url: "https://nextjs.org" },
  { name: "react", url: "https://reactjs.org" },
  { name: "materialui", url: "https://material-ui.com" },
  { name: "storybook", url: "https://storybook.js.org" },
  { name: "react-query", url: "https://react-query.tanstack.com" },
  { name: "formik", url: "https://formik.org" },
  { name: "eslint", url: "https://eslint.org" },
  { name: "prettier", url: "https://prettier.io" },
  { name: "github-actions", url: "https://github.com/features/actions" },
  { name: "docker", url: "https://www.docker.com" },
  { name: "kubernetes", url: "https://kubernetes.io" },
  { name: "helm", url: "https://helm.sh" },
  // { name: "bitnami", url: "https://bitnami.com/stacks/helm" },
  { name: "prometheus", url: "https://prometheus.io" },
  { name: "grafana", url: "https://grafana.com" },
  { name: "lens", url: "https://k8slens.dev" },
  { name: "nginx", url: "https://www.nginx.com" },
  { name: "linode", url: "https://www.linode.com" },
  { name: "cloudflare", url: "https://www.cloudflare.com" },
  {
    name: "stackoverflow",
    url: "https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression",
  },
  { name: "figma", url: "https://www.figma.com" },
  { name: "vscode", url: "https://code.visualstudio.com" },
  { name: "patreon", url: "https://www.patreon.com/lexico" },
  { name: "slack", url: "https://lexico-group.slack.com/archives/C01SN2QN2BF" },
  { name: "wikipedia", url: "https://www.wiktionary.org" },
  { name: "github", url: "https://github.com/JimmyPaolini/Lexico" },
]
