#import "./fragments/PrincipalParts.graphql"
#import "./fragments/Translations.graphql"
#import "./fragments/forms/Forms.graphql"

query SearchLatin($search: String!) {
  searchLatin(search: $search) {
    id
    word
    partOfSpeech
    principalParts {
      ...allPrincipalParts
    }
    translations {
      ...allTranslations
    }
    forms {
      ...allForms
    }
    identifiers
  }
}
