query GetText($id: String!) {
  getText(id: $id) {
    id
    title
    lines {
      id
      line
      lineNumber
    }
    book {
      id
      title
    }
    author {
      name
      fullname
    }
  }
}
