name: deploy
on:
  release:
    types:
      - created
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Libraries
        run: |
          npm install
          cd server && npm install
          cd ../web && npm install
          cd ..
      - name: Hello, World!
        run: echo "Hello, World!"
