name: main
on:
  workflow_dispatch:

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Download Postgres
        run: sudo apt-get update && sudo apt-get install postgresql
      - name: Npm Install
        run: npm install && cd ingestion && npm install
      - name: Login Kubectl
        run: |
          sudo apt-get update && sudo apt-get install kubectl;
          echo "${{ secrets.KUBE_CONFIG }}" > ${{ github.workspace }}/kubeconfig.yaml;
          export KUBECONFIG=${{ github.workspace }}/kubeconfig.yaml
      - name: Database Port Forward
        run: kubectl port-forward statefulset.apps/database 5432 &
      - name: Update database
        run: cd ingestion && yarn restore ingested

  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Login Docker
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Server Image
        run: >-
          DOCKER_BUILDKIT=1 docker build -f server/server.Dockerfile
          -t jimmypaolini/lexico-server:${{ steps.package-version.outputs.current-version}} .
      - name: Push Server Image
        run: docker push jimmypaolini/lexico-server:${{ steps.package-version.outputs.current-version}}
      - name: Login Kubectl
        run: |
          sudo apt-get update && sudo apt-get install kubectl;
          echo "${{ secrets.KUBE_CONFIG }}" > ${{ github.workspace }}/kubeconfig.yaml;
          export KUBECONFIG=${{ github.workspace }}/kubeconfig.yaml
      - name: Deploy Server Image
        run: kubectl rollout restart deployment server

  web:
    runs-on: ubuntu-latest
    needs: database
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Login Docker
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Web Image
        run: >-
          DOCKER_BUILDKIT=1 docker build -f web/web.Dockerfile
          -t jimmypaolini/lexico-web:${{ steps.package-version.outputs.current-version}} .
      - name: Push Web Image
        run: docker push jimmypaolini/lexico-web:${{ steps.package-version.outputs.current-version}}
      - name: Login Kubectl
        run: |
          sudo apt-get update && sudo apt-get install kubectl;
          echo "${{ secrets.KUBE_CONFIG }}" > ${{ github.workspace }}/kubeconfig.yaml;
          export KUBECONFIG=${{ github.workspace }}/kubeconfig.yaml
      - name: Deploy Web Image
        run: kubectl rollout restart deployment web
