name: release
on:
  workflow_dispatch:

jobs:
  # debug:
  #   name: Debug
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump env
  #       run: env | sort
  #     - name: Dump GitHub context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: echo "$GITHUB_CONTEXT"

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Download Postgres
        run: apt-get update && apt-get install postgresql
      - name: get-npm-version
        id: version
        uses: martinbeentjes/npm-get-version-action@master

  login:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Login Docker
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - name: Check Kubernetes
        run: kubectl get node,deployment,sts,pod,ingress,service,pvc,pv,secret

  database:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install Lexico
        run: npm install
      - name: Install Ingestion
        run: cd ingestion && npm install
      - name: Update database
        run: cd ingestion && yarn restore ingested

  server:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Build Server Image
        run: DOCKER_BUILDKIT=1 docker build -f server/server.Dockerfile \
          -t jimmypaolini/lexico-server:${{ steps.package-version.outputs.version}} .
      - name: Push Server Image
        run: docker push jimmypaolini/lexico-server:${{ steps.package-version.outputs.version}}
      - name: Deploy Server Image
        run: kubectl rollout restart deployment server

  web:
    runs-on: ubuntu-latest
    needs: [login, database]
    steps:
      - name: Build Web Image
        run: DOCKER_BUILDKIT=1 docker build -f web/web.Dockerfile \
          -t jimmypaolini/lexico-web:${{ steps.package-version.outputs.version}} .
      - name: Push Web Image
        run: docker push jimmypaolini/lexico-web:${{ steps.package-version.outputs.version}}
      - name: Deploy Web Image
        run: kubectl rollout restart deployment web
