name: server
on:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Login Docker
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - name: Build Server Image
        if: steps.cache.outputs.cache-hit != 'true'
        run: >-
          DOCKER_BUILDKIT=1 docker build -f infra/docker/server.Dockerfile .
          -t jimmypaolini/lexico-server:dev
      - name: Push Server Image
        uses: actions-hub/docker@master
        with:
          args: push jimmypaolini/lexico-server
      - name: Login Kubernetes
        run: mkdir ~/.kube && echo "${{secrets.KUBE_CONFIG}}" > ~/.kube/config
      - name: Deploy Server
        run: kubectl rollout restart deployment server -n lexico-dev
